---
- name: Get Database SID
  set_fact:
    database_sid: "{{ database_primary_sid | default(database_standby_sid) }}"

# Ensure Default Scheduler Timezone is set to Europe/London to account for UK Daylight Savings
- name: Set Default Scheduler Timezone
  include: set_scheduler_timezone.yml

# If autotask_windows is not configured for this environment then simply keep the default autotask windows
- name: Set Autotask Windows
  include: set_autotask_windows.yml
  when: autotask_windows is defined
  tags: windows

# If database_autotasks is not configured for this environment then simply keep the default autotask clients
- name: Set Autotask Status
  include: set_autotask_status.yml
  when: database_autotasks is defined
  tags: status

# If statistics_advisor is not configured for this environment then simply keep the current setting
- name: Set Statistics Advisor Status
  include: set_statistics_advisor_status.yml
  when: database_autotasks['statistics_advisor'] is defined
  tags: statistics_advisor
