---
# Define these in NDH group_vars
ndh_cdecopy_source_dir: /opt/tibco/cde/archive
ndh_cdecopy_temp_dir: /opt/tibco/cde/tmp
ndh_cdecopy_azure_storage_account_name:
ndh_cdecopy_azure_storage_container_name: cde
ndh_cdecopy_s3_bucket_name:
ndh_cdecopy_cron:
  - name: cdecopy
    minute: 20
    hour: 23
