---
ansible_python_interpreter: /usr/bin/python3.9

users_and_groups_regular:
  - group: studio-webops
  - group: nart

users_and_groups_system:
  - name: oracle
    group: oinstall
    groups:
      - dba
      - wheel
  - name: bobj
    group: binstall
    groups:
      - dba
      - sapsys

set_ec2_hostname_mode: "short"

server_type_roles_list:
  - ansible-requirements
  - sshd-config
  - users-and-groups
  - sudoers
  - get-ec2-facts
  - set-ec2-hostname
  - disable-ipv6
  - disable-firewall
  - time
  - packages
  - message-of-the-day
  - amazon-ssm-agent
  - amazon-cli
  - ansible-script
  - epel
  - disks
  - selinux-config
  - oracle-19c-client
  - filesystems
  - sap-bip-4
  # - collectd
  # - amazon-cloudwatch-agent
  # - amazon-cloudwatch-agent-collectd
  # - collectd-service-metrics
  # - collectd-textfile-monitoring

roles_list: "{{ (ami_roles_list | default([]) | difference(server_type_roles_list | default([]))) + (server_type_roles_list | default([])) }}"

packages_yum_update_on_build: []
packages_yum_install:
  - bind-utils
  - nano
  - vim
  - make
  - gdb
  - libnsl
  - libnsl.i686
  - libnsl2
  - libnsl2.i686
  - libstdc++-8.5.0-23.el8_10.i686 # latest version runs into dependency issue
  - libstdc++.x86_64
  - glibc.i686
  - glibc.x86_64
  - libX11.i686
  - libX11.x86_64
  - libXext.i686
  - libXext.x86_64
  # - expat.i686
  - expat.x86_64
  - libxcrypt.i686
  - libgcc.i686
  - libgcc.x86_64
  - libXcursor.i686
  - libXcursor.x86_64
  - libXrender.i686
  - libXrender.x86_64
  - libXfixes.i686
  - libXfixes.x86_64
  - libxcb.i686
  - libxcb.x86_64
  - libXau.i686
  - libXau.x86_64
  - ksh
  - nfs-utils
  - psmisc
  - tcsh
  - uuidd
  - xz-libs.i686
  - openldap-clients

disks_mount:
  - ebs_device_name: /dev/sdb
    dir: /u01
    fstype: xfs
  - ebs_device_name: /dev/sdc
    dir: /u02
    fstype: xfs
  - ebs_device_name: /dev/sds
    dir: swap
    fstype: swap

timezone: "Europe/London"
filesystems_mount: "{{ bip_filesystems_mount|default([]) }}"
oracle_client_conf: "{{ sap_bip_oracle_client_conf }}"
sap_bip_responsefile: response.app.ini
sap_bip_sia_name_app: "{{ ec2.tags.Name | regex_replace('delius-') | replace('-','') }}" # max length 13

# collectd_monitored_services_servertype:
#  - metric_name: service_status_os
#    metric_dimension: chronyd
#    shell_cmd: "systemctl is-active chronyd"
#  - metric_name: service_status_app
#    metric_dimension: service_sapbobj
#    shell_cmd: "pgrep java -u bobj"
