---
- name: Remove previous response file (use root in case left from bootstrap)
  file:
    path: /tmp/ocm.rsp
    state: absent
  become_user: root

- name: Copy OPatch response file
  copy:
    src: ocm.rsp
    dest: /tmp/ocm.rsp

# The fuser utility is not installed as a matter of course so we set OPATCH_NO_FUSER to workaround this
- name: Rollback earlier patch from {{ oracle_home }}
  shell: |
    export PATH=$PATH:{{ oracle_home }}/bin 
    export OPATCH_NO_FUSER=true
    cd {{ patch_directory }}/{{ patch_number }}
     {{ oracle_home }}/OPatch/opatch rollback -silent -id {{ patch_to_replace }}
  when: patch_to_replace != 'none'

- name: Use OPatch to install the patch {{ patch_number }} to {{ oracle_home }}
  shell: |
    export PATH=$PATH:{{ oracle_home }}/bin 
    export OPATCH_NO_FUSER=true
    cd {{ patch_directory }}/{{ patch_number }}
     {{ oracle_home }}/OPatch/opatch apply -silent -ocmrf /tmp/ocm.rsp

- name: Remove response file
  file:
    path: /tmp/ocm.rsp
    state: absent
