---
#- name: Copy syscon tag release details file for build information
#  ansible.builtin.template:
#    src: "10.3{{ item }}"
#    dest: "{{ item }}"
#    owner: oracle
#    group: oinstall
#  loop:
#    - /home/oracle/tag_release_detail

- name: Create tag directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: oracle
    group: oinstall
    mode: "0755"
  loop:
    - /u01/tag/tagsar/cache
    - /u01/tag/tagsar/logs
    - /u01/tag/tagsar/output
    - /u01/tag/HotPage/logs
#    - /u01/tag/autologoff/logs
#    - /u01/tag/tmp

#- name: Update weblogic files
#  import_tasks: extract-s3-archive.yml
#  vars:
#    weblogic_s3_archives:
#      - /u01/app/oracle/Middleware/forms_home/forms/java/2017-10-02.tgz
#      - /u01/app/oracle/Middleware/forms_home/forms/webutil/win32/2017-08-01.tgz
#      - /u01/app/oracle/Middleware/user_projects/domains/NomisDomain/lib/2008-06-27.tgz

- name: Install nomis tag hotpage and autologoff files
  import_tasks: extract-s3-archive.yml
  vars:
    weblogic_s3_archives:
#      - /u01/tag/static/TAG.gif.tgz
#      - /u01/tag/static/HELP/2018-07-26.tgz
#      - "{{ forms_sources_tgz }}"
      - /u01/tag/tagsar/applib/2008-06-27.tgz
      - /u01/tag/tagsar/deploy/2012-07-25.tgz
      - /u01/tag/tagsar/stylesheets/2024-07-29.tgz
#      - /u01/tag/autologoff/deploy/2013-02-01.tgz
      - /u01/tag/HotPage/deploy/2021-01-23.tgz
#      - /u01/tag/reports/2020-11-10.tgz
#      - /u01/tag/server/2022-05-07.tgz

        # httpd.conf uses $SERVERNAME
        # forms.conf uses FQDN
        # webutiljpi.htm has cache directory set
        # formsweb.conf -- loads of diffs..
        # -- add webUtilArchive=frmwebutil.jar,jacob.jar,icons.jar,tagClient.jar,frmrwinteg.jar,ssce.jar,livecapture.jar.
        # tag.env: try
        # REPORT_SERVER_NAME=RptSvr_forms_instance
