- name: Enable weblogic services
  ansible.builtin.service:
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
    state: "{{ service_state | default('started') }}"
  loop: "{{ services_to_manage | default([
              'weblogic-node-manager',
              'weblogic-server',
              'WLS_FORMS',
              'WLS_REPORTS',
              'weblogic-ohs'
            ]) }}"
